Sync boshrelease with latest cg-uaa merge
18F/cg-cf-release pull request #30
Opened 2016-12-08 16:56 UTC by rogeruiz

- [ ] Update submodules
- [x] Upgrade versions in `config/blob.yml`
- [x] Update blobstore across environments
- [x] Clean up `config/blobs.yml` ( :thinking: )
- [ ] Various job updates

cc: @linuxbozo, @cnelson

2016-12-09 16:55 UTC, rogeruiz commented
The `Add * changes` commits leveraged this script to perform a `diff` between release job files.

```
#!/bin/bash

set -eu

uaa_theirs=~/Developer/cloud.gov/uaa-release
uaa_ours=~/Developer/cloud.gov/cg-cf-release

# shellcheck disable=SC2045
for file in $(ls $uaa_ours/jobs/uaa/templates)
do
  file_name=$(echo "$file" | cut -d '/' -f 2)
  original_file="$uaa_theirs/jobs/uaa/templates/$file_name"
  if [ -a "$original_file" ]
  then
    vimdiff "$original_file" "$uaa_ours/jobs/uaa/templates/$file_name"
  fi
done
```

2016-12-09 16:59 UTC, LinuxBozo commented
@rogeruiz so that script doesn't get lost, maybe make it so it only has to ask for theirs path, and commit to this repo?

2016-12-09 18:04 UTC, LinuxBozo requested changes

2016-12-09 18:04 UTC, LinuxBozo commented on packages/uaa/spec
> +- openjdk/openjdk-1.8.0_101-x86_64-trusty.tar.gz
Given: https://gsa-tts.slack.com/archives/cloud-gov-atlas/p1481303821000750, I would expect more changes here.

2016-12-09 18:27 UTC, rogeruiz commented on packages/uaa/spec
> +- openjdk/openjdk-1.8.0_101-x86_64-trusty.tar.gz
right on. I am now seeing a whole bunch of mess. 😞

2016-12-09 18:27 UTC, rogeruiz commented
Would it be safe to assume that if a deprecated property was removed, that it now needs to be removed from our spec and possibly refactored in our templates?

2016-12-09 18:29 UTC, LinuxBozo commented
@rogeruiz Bingo. I would expect updates to either cg-deploy manifest or secrets or both.

2016-12-12 21:39 UTC, LinuxBozo approved these changes

2016-12-12 21:39 UTC, merged